name: Test zwooc

on:
  push:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: "^1.21.8" # The Go version to download (if necessary) and use.
      - uses: GoTestTools/gotestfmt-action@v2
      - name: Install dependencies
        run: go mod download
      - name: Build
        run: go build -v -o zwooc ./cmd/zwooc/main.go
      - name: Run tests
        run: go test -race -json -v -coverprofile=coverage.txt ./... 2>&1 | tee /tmp/gotest.log | gotestfmt
      - name: Smoke test
        run: ./zwooc -v
